version: '3'

services:
  web:
    image: "docker-node-mongo-todo-app"
    build: .
    command: "node server.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    volumes:
      - web-data:/app/data
      - ./config:/app/config
    networks:
      todo-app-network:
        aliases:
          - web
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      todo-app-network:
        aliases:
          - db

volumes:
  web-data:
  mongo-data:

networks:
  todo-app-network:
    driver: bridge
